name: Version update pipeline

on:
  pull_request:
    types: [closed]
    branches:
    - release
jobs:
  run-script:
    # if: startsWith(steps.branch-names.outputs.current_brunch, 'refs/heads/feature/') || startsWith(steps.branch-names.outputs.current_brunch, 'refs/heads/hotfix/')
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    outputs: 
      old_v: ${{steps.get-old-v.outputs.OLD_VERSION}}
      new_v: ${{steps.get-new-v.outputs.NEW_VERSION}}
    steps:

    - name: Get branch names
      id: branch-names
      uses: tj-actions/branch-names@v8
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.2'
    
    # old v 
    - name: get old_version 
      id: get-old-v
      run: |
        OLD_VERSION=$(cat .github/workflows/version)
        echo "${OLD_VERSION}"
        echo "OLD_VERSION=${OLD_VERSION}" >> $GITHUB_OUTPUT

    - name: update minor
      if: startsWith(steps.branch-names.outputs.current_branch, 'feature')
      run: |
        python .github/workflows/versionUpdateScript.py minor
    
    - name: update patch 
      if: startsWith(steps.branch-names.outputs.current_branch, 'hotfix')  
      run: |
        python .github/workflows/versionUpdateScript.py patch
    
    # new v
    - name: get new_version 
      id: get-new-v
      run: |
        NEW_VERSION=$(cat .github/workflows/version)
        echo "${NEW_VERSION}"
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_OUTPUT


    - name: Configure Git
      run: |
        git config --global user.name "Github Actions Bot"
        git config --global user.email "<>"

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update [${{steps.get-new-v.outputs.NEW_VERSION}}] <- [${{steps.get-new-v.outputs.NEW_VERSION}}]"
        git push origin release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-fixme:
    name: (TST)
    needs: run-script
    uses: LAKAS007/land_devops/.github/workflows/tests.yml@release
    with:
      version: alpha