name: Version update pipeline

on:
  pull_request:
    types: [closed]
    branches:
    - release
jobs:
  run-script:
    # if: startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/hotfix/')
    runs-on: ubuntu-latest
    steps:
    
      - name:
        run: | 
          echo "${{github.ref}}" 
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.13.2'

      # - name: Run Python script
      #   run: |
      #     python versionUpdateScript.py
  test-fixme:
    name: (TST)
    needs: run-script
    uses: LAKAS007/land_devops/.github/workflows/tests.yml@release
    with:
      version: alpha